# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(584, 412)
        Dialog.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, -10, 581, 401))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgba(85,98,112,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(255, 107, 107, 255);\n"
"background-position:calc(100% - 10px)center;\n"
"\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color:rgba(255, 107,107,255);\n"
"}\n"
"\n"
"\n"
"QPushButton#register_button{\n"
"background-color:rgba(85,98,112,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#register_button:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(255, 107, 107, 255);\n"
"background-position:calc(100% - 10px)center;\n"
"\n"
"}\n"
"QPushButton#register_button:hover{\n"
"background-color:rgba(255, 107,107,255);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(260, 50, 291, 341))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 241, 371))
        self.label_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 112, 255), stop:1 rgba(255, 107, 107, 255));\n"
"border-radius:10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(390, 110, 71, 16))
        self.label_3.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.email_field = QtWidgets.QLineEdit(self.widget)
        self.email_field.setGeometry(QtCore.QRect(340, 180, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_field.setFont(font)
        self.email_field.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgbs(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"paddin-bottom:7px;\n"
"\n"
"\n"
"")
        self.email_field.setObjectName("email_field")
        self.password_field = QtWidgets.QLineEdit(self.widget)
        self.password_field.setGeometry(QtCore.QRect(340, 240, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_field.setFont(font)
        self.password_field.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgbs(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"paddin-bottom:7px;\n"
"\n"
"\n"
"")
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setObjectName("password_field")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(370, 310, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(120, 140, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255,255,255,200);\n"
"font: 87 17pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(130, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,255,255,200);\n"
"font: 87 18pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.close_btn = QtWidgets.QPushButton(self.widget)
        self.close_btn.setGeometry(QtCore.QRect(520, 60, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("color:rgba(255, 107, 107, 255);\n"
"background-color:rgba(85,98,112,255)")
        self.close_btn.setObjectName("close_btn")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(140, 370, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgba(255,255,255,200);\n"
"font: 87 10pt \"Arial Black\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(110, 310, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgba(255,255,255,200);\n"
"font: 87 15pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(80, 320, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgba(255,255,255,200);\n"
"font: 87 15pt \"Arial Black\";")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(120, 220, 121, 101))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.register_button = QtWidgets.QPushButton(self.widget)
        self.register_button.setGeometry(QtCore.QRect(390, 360, 75, 23))
        self.register_button.setObjectName("register_button")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(330, 340, 191, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_input = QtWidgets.QLabel(self.widget)
        self.label_input.setGeometry(QtCore.QRect(340, 280, 181, 20))
        self.label_input.setStyleSheet("font: 87 9pt \"Arial Black\";color:red;")
        self.label_input.setText("")
        self.label_input.setObjectName("label_input")
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.label_2.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "LOGIN"))
        self.email_field.setPlaceholderText(_translate("Dialog", "Email"))
        self.password_field.setPlaceholderText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "LOGIN"))
        self.label_4.setText(_translate("Dialog", "Facebook "))
        self.label_5.setText(_translate("Dialog", "Scraper"))
        self.close_btn.setText(_translate("Dialog", "X"))
        self.label_6.setText(_translate("Dialog", "2022-2023"))
        self.label_7.setText(_translate("Dialog", "≪ ◦ TCSI ◦ ≫"))
        self.register_button.setText(_translate("Dialog", "REGISTER"))
        self.close_btn.setText(_translate("Dialog", "X"))

